### ISSUE TITLE
On deprecated metrics

### ISSUE THREAD

**Issue by runar-rkmedia** [nikolaydubina/grafana-otel-go-runtime#1]
First, thank you for creating this dashboard.

I was wondering a bit about the wording on the readme:

> Only non-deprecated metrics as of 2024-09-28.

But as far as I can see, this does use the deprecated metrics, according to https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/runtime#pkg-overview .

The non-deprecated metrics are all prefixed with `runtime`, are they not?

**Comment by nikolaydubina** [comment]
it is opposite. these are the new metrics. 
<img width="888" alt="image" src="https://github.com/user-attachments/assets/5a4c4ebc-b94a-4106-a815-9db5578f8d43" />

sometime ago I talked to owner/implementer of otel go runtime. he told me to use these metrics.

> ... Note that we are currently working on a new set of runtime metrics, which replace the existing ones: https://opentelemetry.io/docs/specs/semconv/runtime/go-metrics/.  You can enable the new ones by setting the env var `OTEL_GO_X_DEPRECATED_RUNTIME_METRICS=false`

yeah, it can be little not intuitive, but goes extra mile for non-breaking migration

**Comment by runar-rkmedia** [comment]
Ok, right, I guess I was just confused about the wording on the package pkg-page. 

Thank you for clearing this up :)

I'll just close this issue, then.
